### PR TITLE
Modification to `scipy_integrate_ode_run` In braket_ahs local simulator

### PR DESCRIPTION
**Pull request by weinbe58**
*Issue #, if available:*

N/A this PR attempt to improve the performance of `braket_ahs` local simulator. 

*Description of changes:*

For Analog solvers, it is generally more efficient to apply the operators to the state vector and sum the vectors instead of the current implementation, which sums up the operators and then applies that matrix to the state. 

I am unsure if there are any benchmarks for `braket_ahs` local simulator but It is hard to tell based on what I saw in the benchmarks. If need be I can try to implement a simple benchmark to demonstrate that this will be an improvement. 

*Testing done:*

* Unit tests pass
* Performance analysis shows a regression. However, I am unsure if my changes affect the benchmarks.  

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

#### General

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-braket-default-simulator-python/blob/main/CONTRIBUTING.md) doc
- [x] I used the commit message format described in [CONTRIBUTING](https://github.com/aws/amazon-braket-default-simulator-python/blob/main/CONTRIBUTING.md#commit-your-change)
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-braket-default-simulator-python/blob/main/README.md) and [API docs](https://github.com/aws/amazon-braket-default-simulator-python/blob/main/CONTRIBUTING.md#documentation-guidelines) (if appropriate)

#### Tests

- [x] I have added tests that prove my fix is effective or that my feature works (if appropriate)
- [x] I have checked that my tests are not configured for a specific region or account (if appropriate)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by weinbe58** [comment]
I ran a profiler on the new code with 10 atoms and got the following:

```
         ncalls  tottime   percall  cumtime  percall  filename:lineno(function)
before:      1    0.011    0.011    30.024   30.024   scipy_solver.py:16(scipy_integrate_ode_run)
after:       1    0.009    0.009    15.366   15.366   scipy_solver.py:16(scipy_integrate_ode_run)

```

**Comment by maolinml** [comment]
I have checked with PR with examples 00, 02 and 05. The examples run successfully. Despite I didn't see significant speed up with these examples, the proposed changes indeed make sense, and will provide speed up for larger examples as shown in the attached tests. Hence I approve this PR.

**Review by maolinml — APPROVED** [review]

**Comment by weinbe58** [comment]
So currently this should only work for registers with 10 or more atoms but I think I can look at the numpy solver where a similar change can be made.

**Comment by maolinml** [comment]
Oh right I forgot that, that means what I was doing is not really testing the PR here because the examples are using less than 10 atoms. But nevertheless, I think the PR is correct. For the numpy solver, constructing the Hamiltonian is not avoidable because of this line https://github.com/aws/amazon-braket-default-simulator-python/blob/33074bdf75023fd9d7731c77018443c6927074b1/src/braket/analog_hamiltonian_simulator/rydberg/numpy_solver.py#L98. So not sure if similar things can be done there.

**Comment by weinbe58** [comment]
I can always do another PR, but from what I've seen the solver for a small number of atoms is not noticeablely slow from my experience

**Comment by maolinml** [comment]
Yeah for smaller number of atoms, the current implementation may be efficient enough. I will let one of the engineers in Braket to take a look at this PR, then we can merge it. Thanks for the contribution!

**Pull request merged**
